name = MALE_TUXEDO
scale = 1
filename = http://metaverse.bashora.com/avatars/MALE_TUXEDO.fbx
marketplaceID = {00000000-0000-0000-0000-000000000000}
texdir = textures
joint = jointEyeLeft = LeftEye
joint = jointRoot = Hips
joint = jointEyeRight = RightEye
joint = jointLean = Spine
joint = jointNeck = Neck
joint = jointHead = Head
joint = jointRightHand = RightHand
joint = jointLeftHand = LeftHand
jointIndex = LeftHandPinky4_end = 64
jointIndex = RightHandPinky4 = 34
jointIndex = RightHandPinky1 = 31
jointIndex = EyeRight = 2
jointIndex = LeftForeArm = 58
jointIndex = LeftHandMiddle4_end = 74
jointIndex = LeftHandThumb4_end = 84
jointIndex = RightHandIndex4 = 49
jointIndex = RightToeBase_end = 12
jointIndex = LeftToeBase = 16
jointIndex = RightEye_end = 24
jointIndex = LeftHandMiddle3 = 72
jointIndex = LeftHandIndex4_end = 79
jointIndex = Teeth = 3
jointIndex = LeftHandPinky1 = 60
jointIndex = Neck = 21
jointIndex = RightHandThumb3 = 53
jointIndex = RightHandThumb1 = 51
jointIndex = RightHandMiddle2 = 42
jointIndex = RightHandMiddle3 = 43
jointIndex = LeftHandRing2 = 66
jointIndex = LeftHandPinky4 = 63
jointIndex = LeftHandRing4_end = 69
jointIndex = RightUpLeg = 8
jointIndex = Head = 22
jointIndex = RightHandMiddle4 = 44
jointIndex = RightHandRing3 = 38
jointIndex = RightHandRing4_end = 40
jointIndex = LeftHandThumb3 = 82
jointIndex = LeftUpLeg = 13
jointIndex = LeftHandIndex2 = 76
jointIndex = LeftEye_end = 26
jointIndex = LeftEye = 25
jointIndex = RightToeBase = 11
jointIndex = RightForeArm = 29
jointIndex = EyeLeft = 4
jointIndex = LeftHandIndex3 = 77
jointIndex = LeftFoot = 15
jointIndex = RightHandIndex4_end = 50
jointIndex = SUITE1 = 1
jointIndex = LeftHandThumb1 = 80
jointIndex = HAIR = 0
jointIndex = RightHandMiddle4_end = 45
jointIndex = RightArm = 28
jointIndex = RightHandMiddle1 = 41
jointIndex = RightHandIndex1 = 46
jointIndex = Spine = 18
jointIndex = RightHand = 30
jointIndex = RightShoulder = 27
jointIndex = RightHandIndex3 = 48
jointIndex = LeftHandRing3 = 67
jointIndex = LeftLeg = 14
jointIndex = LeftShoulder = 56
jointIndex = RightHandRing2 = 37
jointIndex = Spine1 = 19
jointIndex = RightHandThumb4_end = 55
jointIndex = LeftHandIndex4 = 78
jointIndex = RightHandThumb2 = 52
jointIndex = LeftHandThumb4 = 83
jointIndex = RightHandRing1 = 36
jointIndex = RightHandPinky4_end = 35
jointIndex = LeftHandMiddle1 = 70
jointIndex = Armature = 6
jointIndex = RightHandPinky2 = 32
jointIndex = LeftHandPinky2 = 61
jointIndex = LeftHandRing1 = 65
jointIndex = LeftHandPinky3 = 62
jointIndex = RightHandPinky3 = 33
jointIndex = RightEye = 23
jointIndex = LeftArm = 57
jointIndex = LeftHand = 59
jointIndex = RightLeg = 9
jointIndex = Spine2 = 20
jointIndex = Body = 5
jointIndex = Hips = 7
jointIndex = LeftToeBase_end = 17
jointIndex = RightHandIndex2 = 47
jointIndex = RightHandThumb4 = 54
jointIndex = LeftHandIndex1 = 75
jointIndex = RightFoot = 10
jointIndex = RightHandRing4 = 39
jointIndex = LeftHandRing4 = 68
jointIndex = LeftHandMiddle2 = 71
jointIndex = LeftHandThumb2 = 81
jointIndex = LeftHandMiddle4 = 73
